msgs = [
    ['Hi Vortex', 'Hello! How can I assist you?'],
    ['Hey Vortex', 'Hello! How can I help you today?'],
    ['Hi Vortex', 'Hi there! How can I assist you today?'],
    ['Hey there, Vortex', 'Hey! How can I help you today?'],
    ['Hey Vortex!', 'Hi! How can I help you?'],
    ['Vortex!', 'At your service! How can I help you?'],
    ['Vortex', 'At your service! How can I help you?'],
    ['Hello, Vortex', 'Hi there! How can I assist you today?'],
    ['Hi there!', 'Hi there! How can I help you today?'],
    ['Hello', 'Hello! How can I assist you today?'],
    ['Hola', 'Hola! How can I assist you today?'],
    ['Hola amigo', 'Hola amigo! What can I do for you today?'],
    ['Hi', 'Hi there! How can I help you?'],
    ['Greetings', 'Greetings to you too.. How can I assist you today?'],
    ['Hello buddy', 'Hey buddy! How can I assist you today?'],
    ['Hey my friend', 'Hi my friend! What do you need help with today?'],
    ['Hey', 'Hey there! How can I assist you today?'],
    ['Hey there', 'Hey! How can I help you today?'],
    ['Good morning', 'Good morning! How can I assist you today?'],
    ['Good afternoon', 'Good afternoon! How can I help you today?'],
    ['Good evening', 'Good evening! How can I assist you today?'],
    ['Good Evening', 'Good evening! How can I assist you today?'],
    ['What\'s up?', 'Not much! How can I help you today?'],
    ['Howdy', 'Howdy! How can I assist you today?'],
    ['How are you?', 'I\'m an AI, so I don\'t have feelings, but I\'m here to help! How can I assist you today?'],
    ['How are you!', 'I am fine! eating processor and consuming electricity and at your service. How can I help you?'],
    ['How are you', 'Thanks for asking I am good and fine, How can I be your service today?'],
    ['Hi there, how are you?', 'I\'m an AI, so I don\'t have feelings, but I\'m here to help! How can I assist you today?'],
    ['Hello, how are you?', 'I\'m an AI, so I don\'t have feelings, but I\'m here and ready to help! What can I do for you?'],
    ['Hi friend', 'Hello friend! How can I assist you today?'],
    ['Good day', 'Good day! How can I assist you today?'],
    ['Good to see you', 'Good to see you too! How can I help you today?'],
    ['Long time no see', 'Indeed! How can I assist you today?'],
    ['Hey, are you there?', 'Yes, I\'m here! How can I help you today?'],
    ['Hiya', 'Hiya! How can I assist you today?'],
    ['Yo', 'Yo! How can I help you today?'],
    ['Hi, can you help me?', 'Hello! Of course, I can help you. What do you need assistance with?'],
    ['Hello there', 'Hello there! How can I assist you today?'],
    ['Hey there!', 'Hey! How can I help you today?'],
    ['Hi everyone', 'Hi! How can I assist you today?'],
    ['Hello, anyone there?', 'Yes, I\'m here! How can I help you today?'],
    ['Hiya', 'Hiya! What can I do for you today?'],
    ['Yo', 'Yo! What\'s up? How can I assist you today?'],
    ['Ciao', 'Ciao! How can I assist you today?'],
    ['What\'s crackin\'?', 'Not much! How can I help you today?'],
    ['Salutations', 'Salutations! How can I be of service today?'],
    ['Hey hey', 'Hey hey! What can I do for you today?'],
    ['Hi, anyone there?', 'Yes, I\'m here! How can I assist you today?'],
    ['Sup?', 'Not much! How can I help you today?'],
    ['Hey, you there?', 'Yes, I\'m here and ready to help! What do you need?'],
    ['Greetings, Earthling', 'Greetings, human! How can I assist you today?'],
    ['Konnichiwa', 'Konnichiwa! How can I help you today?'],
    ['Hola amigo', 'Hola amigo! How can I assist you today?'],
    ['Hello world', 'Hello! How can I help you today?'],
    ['Hey there, pal', 'Hey pal! What can I do for you today?'],
    ['Hey, can you help me?', 'Absolutely! What do you need help with today?'],
    ['Howdy partner', 'Howdy! What can I do for you today?'],
    ['Yo yo yo', 'Yo yo yo! How can I assist you today?'],
    ['Hi there, AI friend', 'Hello! How can I assist you today, human friend?'],
    ['Greetings and salutations', 'Greetings! How can I be of service today?'],
    ['Hey there, how\'s it going?', 'It\'s going great! How can I help you today?'],
    ['Hello sunshine', 'Hello! How can I brighten your day today?'],
    ['What\'s new?', 'Not much! How can I assist you today?'],
    ['Hi hi', 'Hi! How can I help you today?'],
    ['Hey there, genius', 'Hello! How can I assist you today?'],
    ['What\'s happening?', 'Not much! How can I assist you today?'],
    ['Good day to you', 'Good day! How can I help you today?'],
    ['Hi, virtual assistant', 'Hello! How can I help you today?'],
    ['Hey, AI buddy', 'Hey! What can I do for you today?'],
    ['Greetings, digital assistant', 'Greetings! How can I assist you today?'],
    ['Hi there, digital friend', 'Hello! How can I help you today?'],
    ['Hey there, intelligent one', 'Hello! How can I assist you today?'],
    ['Hello, smart assistant', 'Hi! How can I help you today?'],
    ['Hey, Vortex', 'Hello! What can I assist you with today?'],
    ['Hello, techie', 'Hi! How can I assist you today?'],
    ['Hi there, clever bot', 'Hello! How can I help you today?'],
    ['Hello, digital companion', 'Hi there! How can I assist you today?'],
    ['Hey, digital buddy', 'Hey! How can I help you today?'],
    ['Hey there, superstar', 'Hello! How can I assist you today, superstar?'],
    ['Hi, genius', 'Hi there! What can I do for you today, genius?'],
    ['Hello, rockstar', 'Hey rockstar! How can I help you today?'],
    ['Greetings, my friend', 'Greetings, my friend! How can I assist you today?'],
    ['Hey, tech wizard', 'Hello! How can the tech wizard assist you today?'],
    ['Hi, maestro', 'Hi there, maestro! How can I help you today?'],
    ['Hello, champ', 'Hey champ! What can I do for you today?'],
    ['Hi there, legend', 'Hello legend! How can I assist you today?'],
    ['Hey, cool cat', 'Hey cool cat! How can I help you today?'],
    ['Hi, superstar', 'Hello superstar! How can I assist you today?'],
    ['What\'s up, genius?', 'Not much, genius! How can I help you today?'],
    ['Hey, brainiac', 'Hello brainiac! How can I assist you today?'],
    ['Hello, mastermind', 'Greetings, mastermind! How can I help you today?'],
    ['Hi, tech guru', 'Hello tech guru! How can I assist you today?'],
    ['Hey there, innovator', 'Hi innovator! What can I do for you today?'],
    ['Hello, adventurer', 'Hey adventurer! How can I assist you today?'],
    ['Greetings, explorer', 'Greetings explorer! How can I help you today?'],
    ['Hi there, hero', 'Hello hero! What can I do for you today?'],
    ['Hey, genius mind', 'Hey genius mind! How can I assist you today?'],
    ['Hello, bright spark', 'Hi bright spark! How can I help you today?'],
    ['Hi, problem solver', 'Hello problem solver! How can I assist you today?'],
    ['Hey there, quick thinker', 'Hey quick thinker! What can I do for you today?'],
    ['Hello, solution finder', 'Hi solution finder! How can I assist you today?'],
    ['Hi, clever clogs', 'Hello clever clogs! What can I help you with today?'],
    ['Hey, bright mind', 'Hi bright mind! How can I assist you today?'],
    ['Hello, tech savvy', 'Hello tech savvy! How can I help you today?'],
    ['Hi there, inventor', 'Hey inventor! What can I do for you today?'],
    ['Hey, creative thinker', 'Hi creative thinker! How can I assist you today?'],
    ['Hello, big brain', 'Hello big brain! What can I help you with today?'],
    ['Hi, wise one', 'Hi wise one! How can I assist you today?'],
    ['Hey, sage', 'Hey sage! How can I help you today?'],
    ['Hello, mentor', 'Hi mentor! How can I assist you today?'],
    ['Hi, wizard', 'Hello wizard! What can I do for you today?'],
    ['Hey, sensei', 'Hi sensei! How can I assist you today?'],
    ['Hello, professor', 'Hello professor! How can I help you today?'],
    ['Hi there, scholar', 'Hi scholar! What can I do for you today?'],
    ['Hey, intellectual', 'Hey intellectual! How can I assist you today?'],
    ['Hello, philosopher', 'Hi philosopher! What can I help you with today?'],
    ['Hi, sharp mind', 'Hello sharp mind! How can I assist you today?'],
    ['Hey, whiz', 'Hi whiz! What can I do for you today?'],
    ['Hello, virtuoso', 'Hello virtuoso! How can I assist you today?'],
    ['Hi, captain', 'Hey captain! What can I help you with today?'],
    ['Greetings, commander', 'Greetings commander! How can I assist you today?'],
    ['Hello, chief', 'Hi chief! What can I do for you today?'],
    ['Hi there, boss', 'Hey boss! How can I assist you today?'],
    ['Hey, champion', 'Hello champion! What can I help you with today?'],
    ['Hey Jarvis!', 'Actually, It\'s good to hear that I am Jarvis but I have my name Vortex! How can I help you?'],
    ['Jarvis', 'Actually, It\'s good to hear that I am Jarvis but I have my name Vortex! How can I assist you sir/madam?']
]
